config/routes.rb
Fiigii::Application.routes.draw do
  post "search/user_search"

  post "search/status_search"

  resources :interests

  resources :statuses do
    member do
      get :good, :bad, :comments
    end
  end

  resources :users do
    member do
      get :following, :followers, :friends_timeline
      get :favourites, :timeline, :reset, :comments
    end
  end

  controller :session do
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :comments

  resources :topics

  resources :relationships

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  #before_filter :signed_in_user, 
  #              only: [:create, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all(limit: 100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses.as_json(user: current_user) }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status.as_json(user: current_user)}
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status.as_json(user: current_user)}
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    json_data = params[:status]
    if json_data && json_data[:content]
      @status = Status.new(content: json_data[:content])
      if json_data[:topics]
        json_data[:topics].each do |topic|
          @status.topics << topic
        end
      end
      @status.retweeted_id = json_data[:retweeted_id]
      respond_to do |format|
        if @status.save
          current_user.statuses << @status
          format.html { redirect_to @status, notice: 'Status was successfully created.' }
          format.json { render json: @status.as_json(user: current_user), status: :created, location: @status }
        else
          format.html { render action: "new" }
          format.json { render json: @status.errors, status: :unprocessable_entity }
        end
      end
    else
      render json: {}, status: :unprocessable_entity
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  #GET /statuses/1/good.json
  def good
    @status = Status.find(params[:id])
    respond_to do |format|
      if @status
        @status.good!(current_user)
        format.json { render json: @status.as_json(user: current_user) }
      else
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /statuses/1/bad.json
  def bad
    @status = Status.find(params[:id])
    respond_to do |format|
      if @status
        @status.bad!(current_user)
        format.json { render json: @status.as_json(user: current_user) }
      else
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /statuses/1/comments.json
  def comments
    @status = Status.find(params[:id])
    @comments = @status.comments.limit(100)
    respond_to do |format|
      format.json { render json: @comments.as_json(user: current_user) }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :retweeted_id %><br />
    <%= f.number_field :retweeted_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Retweeted</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.content %></td>
    <td><%= status.retweeted_id %></td>
    <td><%= status.user_id %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>

<p>
  <b>Retweeted:</b>
  <%= @status.retweeted_id %>
</p>

<p>
  <b>User:</b>
  <%= @status.user_id %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>