config/routes.rb
Fiigii::Application.routes.draw do
  post "search/user_search"

  post "search/status_search"

  resources :interests

  resources :statuses do
    member do
      get :good, :bad, :comments
    end
  end

  resources :users do
    member do
      get :following, :followers, :friends_timeline
      get :favourites, :timeline, :reset, :comments
    end
  end

  controller :session do
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :comments

  resources :topics

  resources :relationships

end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  # POST /relationships
  # POST /relationships.json
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)

    respond_to do |format|
      format.json { render json: @user.as_json(user: current_user) }
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @user = User.find(params[:id])
    current_user.unfollow!(@user)

    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br />
    <%= f.text_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followed_id %><br />
    <%= f.text_field :followed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<h1>Listing relationships</h1>

<table>
  <tr>
    <th>Follower</th>
    <th>Followed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relationships.each do |relationship| %>
  <tr>
    <td><%= relationship.follower_id %></td>
    <td><%= relationship.followed_id %></td>
    <td><%= link_to 'Show', relationship %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
    <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Follower:</b>
  <%= @relationship.follower_id %>
</p>

<p>
  <b>Followed:</b>
  <%= @relationship.followed_id %>
</p>


<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>